### ISSUE TITLE
Date and Time Utilities Category

### ISSUE THREAD

**Issue by matheus-rodrigues00** [matheus-rodrigues00/utils#3]
Create a DateAndTime category, the starting methods can be:
getTimezoneOffset: This method retrieves the user's current timezone offset from UTC.
getGreeting: This method takes the timezone offset as input and returns a suitable greeting based on the current time.

**Comment by giri-madhan** [comment]
Hello, @matheus-rodrigues00! May I handle this task for you? I can create a `.ts` file and add some utility functions for the DateAndTime category.

**Comment by matheus-rodrigues00** [comment]
> Hello, @matheus-rodrigues00! May I handle this task for you? I can create a `.ts` file and add some utility functions for the DateAndTime category.

Of course, I've saw your commit here, just making a few tests to approve ✅

**Comment by giri-madhan** [comment]
Sure @matheus-rodrigues00 . Thanks for checking!
