### ISSUE TITLE
Create throttle Method 

### ISSUE THREAD

**Issue by matheus-rodrigues00** [matheus-rodrigues00/utils#38]
Implement a throttle method that limits the concurrency of executing promise-returning functions to a specified number.
Method Signature:
```typescript
async function throttle<T>(
  promises: (() => Promise<T>)[],
  maxConcurrency: number
): Promise<T[]> {
  // Implementation goes here
}
```

**Comment by superbrobenji** [comment]
I have a small package for this issue that I recently made, maybe give it a shot: https://www.npmjs.com/package/asyncrify/v/0.1.19?activeTab=readme

**Comment by matheus-rodrigues00** [comment]
@superbrobenji looks great, could you go ahead and implement it?

**Comment by superbrobenji** [comment]
yea, I'll have an open spot tomorrow after work to tackle it quick

**Comment by superbrobenji** [comment]
https://github.com/matheus-rodrigues00/utils/pull/62 Here is the PR for this implementation. Had to do a bit of a workaround to keep alligned with the desired ` Promise<T[]>` return. but works as expected. I made a feature request on asynctify that I'll take on when i have a chance to add this functionality and remove this workaround

**Comment by matheus-rodrigues00** [comment]
Looks great! 
Thanks a lot @superbrobenji
