### ISSUE TITLE
Create maxBy Method

### ISSUE THREAD

**Issue by matheus-rodrigues00** [matheus-rodrigues00/utils#51]
This method is similar to the `max()`, which accepts an array and return the maximum element. Difference is, this method should find the maximum element in an array **based on a provided callback function** that specifies the criteria for comparison. Example: 
```typescript
const arr = [{ 'val': 1 }, { 'val': 4 }, { 'val': 3 }, { 'val': 2 }];

console.log(maxBy(arr, (obj) => obj.n)); // Should return {'val': 4}, since it's the biggest by the criteria.
```

The implementation can be sophisticated, with good type definitions.

**Comment by NullSploit01** [comment]
@matheus-rodrigues00 can you please provide few more examples for this? also, will array always have objects or it can be anything like string `["test", "array"]` or numbers `[1,2,3,4]` or nested inside array `[[1,2], [2,3], [3,4]]` or something else?

**Comment by matheus-rodrigues00** [comment]
@NullSploit01 I don't think we should handle strings or nested arrays, it can be either a numeric array or array of objects, should be fine like that.
Here's couple examples:
```typescript
const people = [{ 'name': 'Alice', 'age': 30 }, { 'name': 'Bob', 'age': 25 }, { 'name': 'Charlie', 'age': 35 }];
console.log(maxBy(people, (person) => person.age)); // Returns {'name': 'Charlie', 'age': 35}
```
```typescript
const products = [{ 'name': 'Product A', 'price': 10 }, { 'name': 'Product B', 'price': 5 }, { 'name': 'Product C', 'price': 15 }];
console.log(maxBy(products, (product) => product.price)); // Returns {'name': 'Product C', 'price': 15}
```
```typescript
// should also work for regular array: number[].
const numbers = [1, 2, 3, 4];
console.log(maxBy(numbers, (num) => num)); // Returns 4
```
